# Generated by Django 3.0.2 on 2020-01-31 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_userdetail_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='phone',
            field=models.CharField(default='a', max_length=13),
            preserve_default=False,
        ),
    ]
