# Generated by Django 3.0.2 on 2020-01-31 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_userdetail_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='phone_country_code',
            field=models.CharField(default='s', max_length=4),
            preserve_default=False,
        ),
    ]
