# Generated by Django 3.0.2 on 2020-01-31 09:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageDeatil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_id', models.CharField(max_length=20, unique=True)),
                ('image_name', models.ImageField(upload_to='uploaded/')),
                ('image_type', models.CharField(choices=[('t1', 'Type 1'), ('t2', 'Type 2')], max_length=3)),
                ('cm_length', models.CharField(max_length=100)),
                ('x1_y1_length', models.CharField(max_length=100)),
                ('x2_y2_length', models.CharField(max_length=100)),
                ('material_information', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('available_qty', models.CharField(max_length=100)),
                ('available_till', models.DateField()),
                ('available_now', models.BooleanField(default=True)),
                ('uploaded_date', models.DateField(auto_now_add=True)),
                ('image_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rmscrapcore.ImageDeatil')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
